# Generated by Django 5.0.6 on 2024-06-13 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='nom de category')),
                ('desc', models.TextField(verbose_name='description de category')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='question')),
                ('proposition', models.CharField(max_length=255, verbose_name='proposition')),
                ('proposition1', models.CharField(max_length=255, verbose_name='proposition1')),
                ('proposition2', models.CharField(max_length=255, verbose_name='proposition2')),
                ('response', models.CharField(max_length=255, verbose_name='response')),
                ('level', models.CharField(choices=[('facile', 'FACILE'), ('moy', 'MOYEN'), ('diff', 'DIFFICILE')], max_length=255, verbose_name='level')),
                ('valeur', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.category', verbose_name='category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Createur de quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('facile', 'FACILE'), ('moy', 'MOYEN'), ('diff', 'DIFFICILE')], max_length=8, verbose_name='level')),
                ('score', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Joueur de quiz')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.category', verbose_name='Score dans cette categorie')),
            ],
        ),
    ]
